version: '3.5'

services:
  sigmon-mongo:
    image: mongo
    volumes:
      - sigmon-mongo-data:/data/db
    network_mode: host
  sigmon-mosquitto:
    image: eclipse-mosquitto
    network_mode: host
  sigmon-app:
    build: .
    environment:
      - SIGMON_ROOT=/usr/src/sigmon
      - SIGMON_DATA=/data/sigmon
      - SIGMON_MONGO_URL=localhost
      - SIGMON_MQQT_PORT=1883
      - SIGMON_WORKER_SLEEP=3
      - SIGMON_PROXIMITY_LOW_RSSI=-38
      - SIGMON_PROXIMITY_HIGH_RSSI=-72
      - SIGMON_OVERVIEW_MINUTES=10
      - SIGMON_SESSION_LENGTH=15
      - SIGMON_SENSOR_CHECK_TIME=5
      - SIGMON_OWN_SSIDS=['MyAP']
      - SIGMON_WATCH_LIST=['nickname','00:00:00:00:00:00']
    network_mode: host
    volumes:
      - ./:/usr/src/sigmon
    depends_on:
      - sigmon-mongo
      - sigmon-mosquitto
    command: ./start 
    tty: true
    privileged: true
volumes:
  sigmon-mongo-data:


